OPT = -O1

default: assignment

assignment: cachetest1 cachetest2

cachetest1:
	gcc cachetest1.c $(OPT) -o cachetest1

cachetest2:
	gcc cachetest2.c $(OPT) -o cachetest2

clean:
	rm -f cachetest1
	rm -f cachetest2

