OPT = -O1

default: assignment

assignment: matrix1 matrix2 matrix3

matrix1:
	gcc matrix1.c $(OPT) -o matrix1

matrix2:
	gcc matrix2.c $(OPT) -o matrix2

matrix3:
	gcc matrix3.c $(OPT) -o matrix3

clean:
	rm -f matrix1
	rm -f matrix2
	rm -f matrix3

